### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [lazyweb-ai/lazyweb-experiments#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by jedwhite** [comment]
Hey thank you! The AGPL-3 suggestion is appreciated and I've added that.
Lots to learn :)
Thanks sincerely!
